### ISSUE TITLE
Missing wireguard binaries

### ISSUE THREAD

**Issue by fernandobarreto** [chirpstack/chirpstack-gateway-os#93] opened 2022-10-28 16:40 UTC
I was trying to test the Chirpstack 4.0.0 Gateway OS for RaspPi3, and I realized that the wireguard binaries (/usr/bin/wg and /usr/bin/wg-quick) are missing from Gateway OS base image.

**Comment by brocaar** [comment] 2022-11-14 09:29
Thanks for reporting, I can reproduce the issue. This was caused by a syntax change in Yocto, will push a fix shortly.

**Comment by brocaar** [comment] 2022-11-14 10:27
Fixed by the above commit.

**Closed** 2022-11-14 10:27 UTC
